var capituloInicial = "<div class='capitulo capitulo-inicial'><h2>Bem-vindo</h2> <p>Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloA)'>Começar a história</button></div></div>";

var capituloA = "<div class='image'><img src='imagens/iron-giant0.jpeg' /> </div><div class='capitulo'><h2>Conteudo A</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloB1)'>Ir para a Esquerda</button> <button class='btn' onclick='carregarConteudo(capituloB2)'>Ir para a Direita</button></div></div>";

var capituloB1 = "<div class='capitulo'><div class='image'><img src='imagens/iron-giant2.jpg' /> </div><h2>Conteudo B1</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloC1)'>Pegar a tesoura</button> <button class='btn' onclick='carregarConteudo(capituloC2)'>Ir para a Lanterna</button></div></div>";

var capituloB2 = "<div class='image'><img src='imagens/iron-giant1.jpg' /> </div> <div class='capitulo'><h2>Conteudo B2</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloC3)'>Seguir no corredor</button> <button class='btn' onclick='carregarConteudo(capituloC4)'>Pegar o Táxi</button></div></div>";

var capituloC1 = "<iframe width='560' height='315' src='https://www.youtube.com/embed/obLtyj8hfFk' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share' allowfullscreen></iframe> <div class='capitulo'><h2>Conteudo C1</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao início</button> <button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao começo</button></div></div>";

var capituloC2 = " <div class='capitulo'><h2>Conteudo C2</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div class='image'><img src='imagens/iron-giant4.jpg' /> </div> <div><button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao início</button> <button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao começo</button></div></div>";

var capituloC3 = "<iframe width='560' height='315' src='https://www.youtube.com/embed/obLtyj8hfFk' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share' allowfullscreen></iframe> <div class='capitulo'><h2>Conteudo C3</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao início</button> <button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao começo</button></div></div>";

var capituloC4 = "<div class='image'><img src='imagens/iron-giant5.jfif' /> </div> <div class='capitulo'><h2>Conteudo C4</h2> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et quam gravida, sodales nunc non, egestas urna. Nulla quis feugiat libero, eget sollicitudin erat. Pellentesque vulputate arcu at sapien tristique, non bibendum diam aliquam. Quisque at facilisis neque. Integer pretium, ex et consectetur laoreet, turpis magna feugiat velit, ac efficitur odio tortor sed sem. Donec vel leo maximus nisl convallis ornare sit amet id quam. Donec porta aliquet elementum.</p> <div><button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao início</button> <button class='btn' onclick='carregarConteudo(capituloA)'>Voltar ao começo</button></div></div>";

var elemento = document.getElementById("conteudo");

function carregarConteudo(parametro) {
    elemento.innerHTML = parametro;
}

carregarConteudo(capituloInicial);

function mudarTema() {
    var pagina = document.getElementById("corpo");
    //pagina.classList.add("modoEscuro"); // Adiciona uma classe no elemento
    //pagina.classList.remove("modoEscuro"); // Remove uma classe no elemento
    pagina.classList.toggle("modoClaro");
    pagina.classList.toggle("modoEscuro");
}

function mudarEstilos() {
    //Dentro dessa função, escreva o codigo para alterar o estilo do elemento com o id "text". 
    //A cor do texto deve ser verde, o tamanho do texto deve ser 15px e a fonte escolhida deve ser Arial;
    //Escreva sua resposta no espaço abaixo.  
    //Um exemplo de alteração de estilos por javascript: text.style.fontFamily = "Comic Sans MS";
    // font-family: banana;

    text.style.fontFamily = "Comic Sans MS";
    text.style.color = "white";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";

}
